### ISSUE TITLE
Resize controls can be moved outside image

### ISSUE THREAD

**Issue by loginwashere** [evrone/evroneCrop#1]
In demo if you start croping from top border of image it is possible to crop image fragment that is bigget in height than canvas. Doing so crop field resize controls can no be reached.

**Comment by kirs** [comment]
Same problem in Chrome.

**Comment by kirs** [comment]
@evindor ?

**Comment by dkoropenko** [comment]
Hello.
Sorry, but this project is archived.
Works by project no longer conducted.
