### ISSUE TITLE
Aspect ratio bug

### ISSUE THREAD

**Issue by romangetman** [evrone/evroneCrop#2]
Hello,
the resize rectangle is not keeping the aspect ratio. From your example page:

Default on page load:
![screen shot 2014-03-22 at 14 13 45](https://f.cloud.github.com/assets/527267/2490687/c3264bc8-b1bb-11e3-9115-25cc011b4fc5.png)

After resizing:
![screen shot 2014-03-22 at 14 13 55](https://f.cloud.github.com/assets/527267/2490689/d480e036-b1bb-11e3-9060-9a9ba3841a09.png)

On the second screenshot the resize frame is definitely not 16:9, but I can't seem to find the bug and fix it myself as I don't know much of coffeescript and the generated JS version is hard to analyze. Also you can reply in Russian, it's not a problem for me.

**Comment by dkoropenko** [comment]
Hello.
Sorry, but this project is archived.
Works by project no longer conducted.
