### ISSUE TITLE
click without mousemove produces error

### ISSUE THREAD

**Issue by SSilence** [evrone/evroneCrop#3]
When I just click on the image without moving the mouse produces error messages, because no selection was set:

Uncaught TypeError: Cannot read property 'drag' of undefined evroneCrop.js:138
(anonymous function) evroneCrop.js:138
(anonymous function) evroneCrop.js:3
(anonymous function) evroneCrop.js:115
jQuery.event.handle jquery.js:3001

You can test this on your demo: http://evrone.github.io/evroneCrop/
Just click without move the mouse.

I really love your script. Hope you will fix this soon, then I will twitter about this! I will use this inside a node-webkit project.

**Comment by dkoropenko** [comment]
Hello.
Sorry, but this project is archived.
Works by project no longer conducted.
